### ISSUE TITLE
Strengthen custom error test checks

### ISSUE THREAD

**Issue by diego-G** [CMTA/CMTAT#191]
[TODO](https://github.com/CMTA/CMTAT/blob/4cb6320ee4704addfc5ca8f616b6162d98e68d9a/test/common/BaseModuleCommon.js#LL110C1-L110C1)

Related to https://github.com/CMTA/CMTAT/pull/190

Depends on https://github.com/trufflesuite/truffle/issues/5753

**Comment by rya-sge** [comment]
See also [https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2839](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2839)
