### ISSUE TITLE
Update versions

### ISSUE THREAD

**Issue by veorq** [CMTA/CMTAT#31]
npm / node / etc.

openzeppelin-test-helpers -> @openzeppelin/test-helpers

**Comment by veorq** [comment]
Use [foundry](https://book.getfoundry.sh/) instead?

**Comment by sirhill** [comment]
Remove all material stolen from the C-Layer.
There will be legal consequences.

**Comment by veorq** [comment]
Being addressed in https://github.com/CMTA/CMTAT/pull/40 and https://github.com/CMTA/CMTAT/pull/36.
