### ISSUE TITLE
Create RuleEngine example

### ISSUE THREAD

**Issue by veorq** [CMTA/CMTAT#32]
Here or (probly better) as a separate repo/contract.

**Comment by sirhill** [comment]
Remove all material stolen from the C-Layer.
There will be legal consequences.

**Comment by sirhill** [comment]
Btw, if you want to really continue stealing ... have a look at the Ethereum repository.
.... EIP-1592

You are such a joke @veorq

**Comment by veorq** [comment]
In progress in https://github.com/CMTA/RuleEngine/settings
